services:
  - type: web
    name: ikiguia
    env: python
    rootDirectory: ikiguia    
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ikiguia.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ikiguia.settings
      - key: PYTHON_VERSION
        value: 3.10
