# Generated by Django 5.2.4 on 2025-07-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('carreras', models.ManyToManyField(to='usuarios.carrera')),
            ],
        ),
    ]
