# Generated by Django 5.2.4 on 2025-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
