# Generated by Django 5.2.4 on 2025-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_mentoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='habilidades_clave',
            field=models.JSONField(),
        ),
    ]
